# Vectors using Numpy

#### **What is Numpy?**
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are several important differences between NumPy arrays and the standard Python sequences(lists):

*   NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
*   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
*    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
*    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. Numpy is preferred due to its performance in computation.



In [1]:
# Lets Import Numpy
import numpy as np

In [2]:
# TASK: Define Numpy arrays with names: n1, n2
# Reference: https://numpy.org/doc/stable/user/quickstart.html#array-creation

# Your Code:
n1=np.array([1,2,3,4])
n2=np.array([1.1,2.6,7.8,9.2])



print(n1,n1.dtype)
print(n2,n2.dtype)

[1 2 3 4] int64
[1.1 2.6 7.8 9.2] float64


In [4]:
n1.shape

(4,)

In [10]:
# TASK: Redefine n1 as a vector/array with the values 22,33,44 and order of the vector as 1x3

# Your Code:
n1=np.array([22,33,44])
n1.reshape(1,3)



print(n1,n1.shape)

[22 33 44] (3,)


#### Addition

Adding numpy vectors is as simple as performing regular addition in Python.

In [11]:
# TASK: Add vector [2, 2, 2] with n1 from earlier

# Your Code:
n1+([2,2,2])



# Expected output: [24, 35, 46]

array([24, 35, 46])

#### Subtraction

Subtracting numpy vectors is also as simple as performing regular subtraction in Python

In [12]:
# TASK: Subtract vector [2, 3, 4] with n1 from earlier

# Your Code:
n1-[2, 3, 4]



# Expected output: [20, 30, 40]

array([20, 30, 40])

#### Scalar Multiplication/ Element-wise multiplication

This is also very easy to perform. Regular Python is enough or numpy also comes with functions to perform the same

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy-multiply


In [13]:
# TASK: Multiply n1 with 25

# Your Code:
n1*25



# Expected output: [550,  825, 1100]

array([ 550,  825, 1100])

In [14]:
# TASK: perform element-wise multiplication of n1 and [11, 12, 13]. Use numpy's multiply function

# Your Code:
np.multiply(n1,[11, 12, 13])



# Expected output: [242, 396, 572]

array([242, 396, 572])

#### Vector Multiplication

Vector multiplication, or also called dot product of vectors/matrices. Numpy has functions to perform the same

https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy-dot
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape

note: numpy functions also carry additional features for certain scenarios of inputs. The reference mentions all of them, we will be looking only at our required case here.

In [83]:
# TASK: perform vector multiplication of n1 (use numpy reshape:- set order as 3 x 1) and a vector of only 3's, and of order/dimension 1 x 4

# Your Code:
print(n1.reshape(3,1))
# (n1.reshape(3,1)).dot(np.array([3,3,3,3]).reshape(1,4))

np.dot(n1.reshape(3,1),np.array([[3,3,3,3]]))


# Expected Output:
# [[ 66,  66,  66,  66],
#  [ 99,  99,  99,  99],
#  [132, 132, 132, 132]]

[[22]
 [33]
 [44]]


array([[ 66,  66,  66,  66],
       [ 99,  99,  99,  99],
       [132, 132, 132, 132]])

In [85]:
# TASK: perform vector multiplication of n1 and transpose of n1. Use numpy techniques for transpose

# Your Code:
print(n1.transpose())
# print(n1.dot(n1.transpose()))
np.dot(n1,n1.T)

# Expected output: 3059

[22 33 44]


np.int64(3509)

In [86]:
# TASK: Initialize a vector (v1) with prime numbers 1 to 23, with order 3x3. Initialize a vector (v2) as inverse of v1.
# Perform vector multiplication of both and get identityu matrix. Use numpy rounding methods if needed
# https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy-linalg-inv
# https://numpy.org/doc/stable/reference/generated/numpy.round.html#numpy-round

# Your Code:
p=[]
def primeNumber(n):
    for i in range(2,n+1):
        if i==2 or i==3:
            p.append(i)
        for j in range(2,int(n**0.5)+1):
            if i%j==0:
                break
        else: 
            p.append(i)
primeNumber(23)
print(p)

p1=np.array(p).reshape(3,3)
print(p1)
p1_inverse=np.linalg.inv(p1)
print(p1_inverse)
print((p1.dot(p1_inverse)).round())

# Expected output (with or without signs both is ok):
# [[ 1., -0.,  0.],
#  [ 0.,  1.,  0.],
#  [-0., -0.,  1.]]

[2, 3, 5, 7, 11, 13, 17, 19, 23]
[[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
[[-0.07692308 -0.33333333  0.20512821]
 [-0.76923077  0.5        -0.11538462]
 [ 0.69230769 -0.16666667 -0.01282051]]
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


#### Go Through Documentation

https://numpy.org/doc/stable/user/quickstart.html#the-basics

In [87]:
# TASK: Study and perform 3 different universal functions on v1
n2=np.arange(15).reshape(3,5)
print(n2)

print(n2.shape)

print(n2.ndim)

print(n2.dtype)

print(type(n2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
<class 'numpy.ndarray'>
